
#define NUMS ((int)(sizeof sysmetrics) / (sizeof sysmetrics[0]))

struct 
{
	UINT  Inedx; 
	TCHAR * szLabel ; 
	TCHAR * szDesc ; 
}
sysmetrics [] = 
{ 
	 SM_CXSCREEN, TEXT ("SM_CXSCREEN"), 
	 TEXT ("Screen width in pixels"), 
	 SM_CYSCREEN, TEXT ("SM_CYSCREEN"), 
	 TEXT ("Screen height in pixels"), 
	 SM_CXVSCROLL, TEXT ("SM_CXVSCROLL"), 
	 TEXT ("Vertical scroll width"), 
	 SM_CYHSCROLL, TEXT ("SM_CYHSCROLL"), 
	 TEXT ("Horizontal scroll height"), 
	 SM_CYCAPTION, TEXT ("SM_CYCAPTION"), 
	 TEXT ("Caption bar height"), 
	 SM_CXBORDER, TEXT ("SM_CXBORDER"), 
	 TEXT ("Window border width"), 
	 SM_CYBORDER, TEXT ("SM_CYBORDER"), 
	 TEXT ("Window border height"), 
	 SM_CXFIXEDFRAME,TEXT ("SM_CXFIXEDFRAME"), 
	 TEXT ("Dialog window frame width"), 
	 SM_CYFIXEDFRAME,TEXT ("SM_CYFIXEDFRAME"), 
	 TEXT ("Dialog window frame height"), 
	 SM_CYVTHUMB, TEXT ("SM_CYVTHUMB"), 
	 TEXT ("Vertical scroll thumb height"), 
	 SM_CXHTHUMB, TEXT ("SM_CXHTHUMB"), 
	 TEXT ("Horizontal scroll thumb width"), 
	 SM_CXICON, TEXT ("SM_CXICON"), 
	 TEXT ("Icon width"), 
	 SM_CYICON, TEXT ("SM_CYICON"), 
	 TEXT ("Icon height"), 
	 SM_CXCURSOR, TEXT ("SM_CXCURSOR"), 
	 TEXT ("Cursor width"), 
	 SM_CYCURSOR, TEXT ("SM_CYCURSOR"), 
	 TEXT ("Cursor height"), 
	 SM_CYMENU, TEXT ("SM_CYMENU"), 
	 TEXT ("Menu bar height"), 
	 SM_CXFULLSCREEN,TEXT ("SM_CXFULLSCREEN"), 
	 TEXT ("Full screen client area width"), 
	 SM_CYFULLSCREEN,TEXT ("SM_CYFULLSCREEN"), 
	 TEXT ("Full screen client area height"), 
	 SM_CYKANJIWINDOW,TEXT ("SM_CYKANJIWINDOW"), 
	 TEXT ("Kanji window height"), 
	 SM_MOUSEPRESENT, TEXT ("SM_MOUSEPRESENT"), 
	 TEXT ("Mouse present flag"), 
	 SM_CYVSCROLL,TEXT ("SM_CYVSCROLL"), 
	 TEXT ("Vertical scroll arrow height"), 
	 SM_CXHSCROLL,TEXT ("SM_CXHSCROLL"), 
	 TEXT ("Horizontal scroll arrow width"), 
	 SM_DEBUG, TEXT ("SM_DEBUG"), 
	 TEXT ("Debug version flag"),
	 SM_CXSCREEN, TEXT ("SM_CXSCREEN"), 
	 TEXT ("Screen width in pixels"), 
	 SM_CYSCREEN, TEXT ("SM_CYSCREEN"), 
	 TEXT ("Screen height in pixels"), 
	 SM_CXVSCROLL, TEXT ("SM_CXVSCROLL"), 
	 TEXT ("Vertical scroll width"), 
	 SM_CYHSCROLL, TEXT ("SM_CYHSCROLL"), 
	 TEXT ("Horizontal scroll height"), 
	 SM_CYCAPTION, TEXT ("SM_CYCAPTION"), 
	 TEXT ("Caption bar height"), 
	 SM_CXBORDER, TEXT ("SM_CXBORDER"), 
	 TEXT ("Window border width"), 
	 SM_CYBORDER, TEXT ("SM_CYBORDER"), 
	 TEXT ("Window border height"), 
	 SM_CXFIXEDFRAME,TEXT ("SM_CXFIXEDFRAME"), 
	 TEXT ("Dialog window frame width"), 
	 SM_CYFIXEDFRAME,TEXT ("SM_CYFIXEDFRAME"), 
	 TEXT ("Dialog window frame height"), 
	 SM_CYVTHUMB, TEXT ("SM_CYVTHUMB"), 
	 TEXT ("Vertical scroll thumb height"), 
	 SM_CXHTHUMB, TEXT ("SM_CXHTHUMB"), 
	 TEXT ("Horizontal scroll thumb width"), 
	 SM_CXICON, TEXT ("SM_CXICON"), 
	 TEXT ("Icon width"), 
	 SM_CYICON, TEXT ("SM_CYICON"), 
	 TEXT ("Icon height"), 
	 SM_CXCURSOR, TEXT ("SM_CXCURSOR"), 
	 TEXT ("Cursor width"), 
	 SM_CYCURSOR, TEXT ("SM_CYCURSOR"), 
	 TEXT ("Cursor height"), 
	 SM_CYMENU, TEXT ("SM_CYMENU"), 
	 TEXT ("Menu bar height"), 
	 SM_CXFULLSCREEN,TEXT ("SM_CXFULLSCREEN"), 
	 TEXT ("Full screen client area width"), 
	 SM_CYFULLSCREEN,TEXT ("SM_CYFULLSCREEN"), 
	 TEXT ("Full screen client area height"), 
	 SM_CYKANJIWINDOW,TEXT ("SM_CYKANJIWINDOW"), 
	 TEXT ("Kanji window height"), 
	 SM_MOUSEPRESENT, TEXT ("SM_MOUSEPRESENT"), 
	 TEXT ("Mouse present flag"), 
	 SM_CYVSCROLL,TEXT ("SM_CYVSCROLL"), 
	 TEXT ("Vertical scroll arrow height"), 
	 SM_CXHSCROLL,TEXT ("SM_CXHSCROLL"), 
	 TEXT ("Horizontal scroll arrow width"), 
	 SM_DEBUG, TEXT ("SM_DEBUG"), 
	 TEXT ("Debug version flag")
};